### ISSUE TITLE
Connecting to Slack fails due to expired certificate

### ISSUE THREAD

**Issue by pdpinch** [foo-software/bugs#12]
# Summary

1. From the dashboard, I attempted to add a Slack connection. 
2. I logged into my Slack account
3. I was able to choose a channel from my Slack account
3. When I clicked the "Allow" button on slack.com I got the following error message (in Chrome):

> Attackers might be trying to steal your information from www.automated-lighthouse-check.com (for example, passwords, messages, or credit cards). Learn more
NET::ERR_CERT_DATE_INVALID

> This server could not prove that it is www.automated-lighthouse-check.com; its security certificate expired 3 days ago. This may be caused by a misconfiguration or an attacker intercepting your connection. Your computer's clock is currently set to Monday, December 21, 2020. Does that look right? If not, you should correct your system's clock and then refresh this page.

#### Related Issues

Add any related issues here.

# Actual Behavior

"Your connection is not private" message from Chrome

# Expected Behavior

I was expecting to connect to my Slack account, and be able to send notifications to a Slack channel. 

# Environment

Any details about your environment is greatly appreciated. Example below.

- OS: macOS v10.14.6
- Browser: Chrome v84.0.4147.105

# Screenshots

<img width="680" alt="Screen Shot 2020-12-21 at 2 03 54 PM" src="https://user-images.githubusercontent.com/430126/102812906-e79dd200-4395-11eb-82a4-7a4554b936af.png">

**Comment by adamhenson** [comment]
Thanks for providing all those details @pdpinch. I'm very sorry this is happening. `automated-lighthouse-check.com` is our old domain and something in the codebase or Slack settings is pointing to it. Perhaps our SSL for that domain just recently expired which is why the error was not exposed previously (because we are redirecting).

We'll have a fix for this as soon as possible and will report back. This bug has the highest priority.

**Comment by adamhenson** [comment]
@pdpinch - this issue has been addressed. Please try again at your convenience.

The source of this bug was that we did not update a setting in our Slack App ("redirect URL") when we changed domains a while back. We still redirect traffic from the old domain under the hood and this bug wasn't exposed until now, most likely because the SSL was disabled. Our SSL automatically renews, however apparently we were supposed to take an extra step in re-installing it.

## The Fix
1. We implemented a short term fix to re-install the SSL on automated-lighthouse-check.com.
2. We updated the Slack redirect URL and have resubmitted the app with Slack (which could take a few weeks for them to review).
